name: Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16

      - uses: actions/checkout@v3

      - name: Build
        run: GOOS=linux go build -mod=vendor -o main cmd/main.go

      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r lambdaSaver.zip . -i main

      - uses: actions/upload-artifact@v2-preview
        with:
          name: lambda-saver-zip
          path: lambdaSaver.zip
          key: lambdaSaver.zip